name: Create Release On Demand

on: workflow_dispatch

permissions:
  packages: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Run data preprocessor
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python preprocess_data.py
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          otj-boxing-cards.csv
        name: card-csv-${{ steps.date.outputs.date }}
